services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/env/dev.env
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
    env_file:
      - ./backend/env/dev.env
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./backend/env/dev.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 